LOG_INFO_TO_CONSOLE: true
MAX_PLAYERS_IN_GAME: 8
PLAYERS_TO_START: 1
PLAYERS_TO_END: 8
LAPSES_TO_FINISH: 3
TIME_TO_START_GAME_LOBBY: 20
TIME_TO_START_GAME: 30
TIME_TO_FINISH: 60
TIME_TO_END_GAME: 20
SET_Y_SMALL: 1.1
SET_Y_MID: 2.1
SET_Y_BIG: 3.5
DIR_MP_MID: 1.07
DIR_MP_BIG: 4.0
DIR_MP_WATER: 2.5
DIR_MP_ELYTRA: 1.0
SET_Y_ELYTRA: 0.3
SPEED_DURATION: 40
SPEED_AMP: 2
Y_DEATH: 0