name: ${NAME}
version: ${VERSION}
api-version: ${MINECRAFT_VERSION}
main: com.joutak.acerace.AceRacePlugin
description: 'Plugin for AceRace minigame'
authors: ['EnderDissa', 'Stunnerer', 's4dnex']
contributors: ['technosimp']
website: ${WEBSITE}

depend: ['Multiverse-Core']
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:${KOTLIN_VERSION}'

commands:
  ar:
    description: AceRace commands
  cp:
    description: Checkpoints commands
    usage: /cp <setpos1|setpos2|remove|list|reload|clear|info> [index]
    permission: acerace.admin
  zone:
    description: Zone management commands
    usage: /zone <args>
    permission: acerace.admin

permissions:
  acerace.admin:
    default: op
    description: Доступ ко всем командам плагина AceRace
    children:
      mv.bypass.gamemode.*: true
  acerace.spectator:
    default: op
    description: Доступ к команде /ar spectate для наблюдения за играми
    children:
      mv.bypass.gamemode.*: true
      minecraft.command.spectate: true