name: AceRace
version: '$version'
main: com.joutak.acerace.AceRacePlugin
api-version: '1.21'
commands:
  ar:
    description: AceRace commands
    usage: |
      /ar create <type> <name> <world> <x1> <y1> <z1> <x2> <y2> <z2>
      /ar list
      /ar info <name>
      /ar remove <name>